version: '3.8'

services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/myapp
    environment:
      DATABASE_URL: postgres://postgres:password@postgres/myapp_development
      REDIS_URL: redis://redis:6379/0

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_development
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
